### PR TITLE
Disallowed the nav elements while loading the publication articles.

### PR DESCRIPTION
**Pull request by brebaroluk**

### CODE REVIEW

**Comment by PeeEmKay** [comment]
Also contains the changes from the already approved PR5

**Review by PeeEmKay — APPROVED** [review]
Contains PR5 changes as well as the changes for this bug.

**Comment by brebaroluk** [comment]
> Also contains the changes from the already approved PR5

Yes, it's because we're now merging both repos in a single repo under the Nuance repo and i wanted to make sure the fix for the other ticket is also reflecting on the main repo.

**Comment by PeeEmKay** [comment]
Cool - makes sense

**Pull request merged**
